ERROR:py_data_rules.rule_engine:rule evaluation failed for tax_id_versus_scientific_name with exception AssertionError: 
